// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDssURY8OPX-7ZKzQ9vF0H3tLmbw7O145U',
    appId: '1:871866994513:web:d14eee40ac81d89df24d70',
    messagingSenderId: '871866994513',
    projectId: 'chat-app-b7530',
    authDomain: 'chat-app-b7530.firebaseapp.com',
    storageBucket: 'chat-app-b7530.firebasestorage.app',
    measurementId: 'G-FC39M2LSJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ7kGUxoOxI_dHHsgg3r5stVMY1yPcfGs',
    appId: '1:871866994513:android:a72ebc46f084fe97f24d70',
    messagingSenderId: '871866994513',
    projectId: 'chat-app-b7530',
    storageBucket: 'chat-app-b7530.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEpIRQ5Nycs5PY8ICCVPlzj__0kRvNMP0',
    appId: '1:871866994513:ios:c56b17623265f675f24d70',
    messagingSenderId: '871866994513',
    projectId: 'chat-app-b7530',
    storageBucket: 'chat-app-b7530.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEpIRQ5Nycs5PY8ICCVPlzj__0kRvNMP0',
    appId: '1:871866994513:ios:c56b17623265f675f24d70',
    messagingSenderId: '871866994513',
    projectId: 'chat-app-b7530',
    storageBucket: 'chat-app-b7530.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDssURY8OPX-7ZKzQ9vF0H3tLmbw7O145U',
    appId: '1:871866994513:web:b0a0072344ff9642f24d70',
    messagingSenderId: '871866994513',
    projectId: 'chat-app-b7530',
    authDomain: 'chat-app-b7530.firebaseapp.com',
    storageBucket: 'chat-app-b7530.firebasestorage.app',
    measurementId: 'G-DZFPJXTN6Z',
  );

}